# Generated by Django 3.0.3 on 2020-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_auto_20200708_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
